#!/bin/bash
if [ $# -eq 2 ] ; then
	path="/Index/invedio/id/$2"
	while true ; do
		if [ $1 == "snh48" ] ; then
			temp=$(curl -s http://zhibo.ckg48.com$path)
		else
			temp=$(curl -s http://live.$1.com$path)
		fi
		response=$(echo "$temp" | grep '<title>')
		if [ -n "$response" ] ; then
			Status=$(echo "$response" | grep -o '502 Bad Gateway')
			if [ ! -n "$Status" ] ; then
				echo "$temp" | grep -Po -m 1 'https?://[^"]*\.m3u8[^"]*'
				break
			fi
		fi
	done
else
	echo "Usage: $0 <GroupName> <StageID>"
fi
